Query was executed successfully

{x,y} a
{0,0} 1
{0,1} 2
{0,2} 3
{1,0} 4
{1,1} 5
{1,2} 6
{2,0} 7
{2,1} 8
{2,2} 9

[An error expected at this place for the query "select * from mult_1 as m1 join mult_1 as m2 on m1.i=m2.i". And it failed with error code = scidb::SCIDB_SE_SYNTAX::SCIDB_LE_UNKNOWN_ATTRIBUTE_OR_DIMENSION. Expected error code = scidb::SCIDB_SE_SYNTAX::SCIDB_LE_UNKNOWN_ATTRIBUTE_OR_DIMENSION.]

Query was executed successfully

